// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

import java.math.*;

class ProblemTwo{
    public static void main(String args[]){

        double fib = 0;
        long target = 40;
        


        for(long i = 0; i <= target; i++){
            fib = (Math.pow((1 + Math.sqrt(5)), i) -  Math.pow((1 - Math.sqrt(5)), i)) /  (Math.pow(2, i) * Math.sqrt(5)); 
            
        }
        System.out.println((int)fib);

        if((int)fib > 400000){
            System.out.println("True");
        }
        else{
            System.out.println("False");
        }


    }
}